[package]
name = "install-msvc"
version = "0.1.0"
edition = "2024"

[dependencies]
find-msvc-tools = "0.1.9"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tempfile = "3.25.0"
vssetup = { path = "../..", version = "0.3.0" }
